name: powerplay_landing_page
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\img1.jpg
    - assets\img2.jpg
    - assets\img3.jpg
    - assets\img4.jpg
    - assets\img5.jpg
    - assets\img6.jpg
    
    
